---
image:
  name: alpine/helm
  entrypoint: [""]

.template_lint: &template_lint
  stage: lint
  script:
    - test -f values-${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/lint-/}.yaml
    - helm lint . -f values-${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/lint-/}.yaml
  allow_failure: true

.template_render: &template_render
  stage: render
  script:
    - test -f values-${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/render-/}.yaml
    - helm template . -f values-${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/render-/}.yaml > ${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/render-/}.yaml
    - cat ${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/render-/}.yaml
  artifacts:
    paths:
      - ${CI_PROJECT_NAME/platform-configuration-helm-/}-${CI_JOB_NAME/render-/}.yaml
    expire_in: 1 week
  allow_failure: true

stages:
  - lint
  - render

lint-rec1:
  <<: *template_lint

lint-rec2:
  <<: *template_lint

lint-rec3:
  <<: *template_lint

lint-preprod:
  <<: *template_lint

lint-prod:
  <<: *template_lint

render-rec1:
  <<: *template_render

render-rec2:
  <<: *template_render

render-rec3:
  <<: *template_render

render-preprod:
  <<: *template_render

render-prod:
  <<: *template_render
