---
ingress:
  enabled: true
  hosts:
    - host: app1-dev.demo.lan
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: app1-dev-tls
     hosts:
       - app1-dev.demo.lan

volumesAndMounts:
  volumes:
    - name: dev
      hostPath:
        path: /workspace/content-app-app1/sources # matches kind containerPath:
    - name: vol-nginx
      configMap:
        name: cm-nginx
  volumeMounts:
    - name: dev
      mountPath: /usr/share/nginx/html/ # in the container filesystem
    - name: vol-nginx
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      readOnly: true
    - name: vol-nginx
      mountPath: /etc/nginx/fetch_env.js
      subPath: fetch_env.js
      readOnly: true
    - name: vol-nginx
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
      readOnly: true

env:
  fromValues:
    ENV: environnement-app1-dev
