---
_host: &host app1-dev.demo.lan

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: *host
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

volumesAndMounts:
  volumes:
    - name: dev
      hostPath:
        path: /workspace/content-app-app1/sources # matches kind containerPath:
    - name: vol-nginx
      configMap:
        name: cm-nginx
  volumeMounts:
    - name: dev
      mountPath: /usr/share/nginx/html/ # in the container filesystem
    - name: vol-nginx
      mountPath: /etc/nginx/conf.d/default.conf
      subPath: default.conf
      readOnly: true
    - name: vol-nginx
      mountPath: /etc/nginx/fetch_env.js
      subPath: fetch_env.js
      readOnly: true
    - name: vol-nginx
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
      readOnly: true
env:
  fromValues:
    ENV: kind-dev