{{- if .Values.certmanager_selfSigned.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- $fullName := include "app.fullname" . -}}
{{- range .Values.ingress.tls }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ $fullName }}
  commonName: {{ index .hosts 0 | quote }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}
{{- end }}